---
name: Bug Report  
description: File a bug report  
title: "[Bug]: "  
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is the problem?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can the problem be reproduced?
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Solace Product
      description: What Solace product is this directly affecting?
      options:
        - Solace PubSub+ Event Portal
        - Solace PubSub+ Event Broker
        - Solace PubSub+ Insights
        - Solace APIs
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: broker_version
    attributes:
      label: Solace Broker version
      description: What version of the Solace Broker are you using?
    validations:
      required: false
  - type: input
  id: solace_API
  attributes:
    label: Solace API
    description: What Solace API are you using?
  validations:
    required: false
  - type: input
  id: API_version
  attributes:
    label: Solace API version
    description: What version of the Solace API are you using?
  validations:
    required: false
